version: '3.9'

services:
  # MongoDB services
  mongo_db:
    container_name: mongo_db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - "27017:27017"

  # Node.js API services
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/src/app
    env_file:
      - .env
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
